### ISSUE TITLE
Create Comment Model/Associated Routes

### ISSUE THREAD

**Issue by uptonm** [uptonm/Full-Stack-Web-App#1]
# Tasks:
### Mongoose Model:
- [ ] Create mongoose model schema
- [ ] Create link between user and posted comment (User ObjectId)
### Express routes for:
- [ ] Create comment
- [ ] Delete comment
- [ ] Get all comments
- [ ] Get specific comment
- [ ] Get user profile from comment
