### ISSUE TITLE
Create Post Model/Associated Routes

### ISSUE THREAD

**Issue by uptonm** [uptonm/Full-Stack-Web-App#2]
# Tasks:
### Mongoose Model:
- [x] Create mongoose model schema
- [x] Create link between post and comment (Post ObjectId)
### Express routes for:
- [x] Create post
- [x] Delete post
- [x] Get all posts
- [x] Get specific post
- [x] Get comments from post
